
package tc.compiler.tree;

import tc.compiler.Location;
import tc.compiler.tree.visit.TreeVisitor;
import static tc.compiler.tree.Binop.*;

/**
 * AST binary operator node.
 *
 */
public final class BinaryOperator extends Expression
{
  // the operator itself
  private Binop op;

  // the left subtree for the single operand
  private Expression left;

  // the right subtree for the single operand
  private Expression right;

  /** Construct a binary operator node.
   *
   *  @param loc    source code location of operator.
   *  @param op     specific binary operator being constructed.
   *  @param left   the left subtree of the operator.
   *  @param right  the right subtree of the operator.
   */
  public BinaryOperator(final Location loc, final Binop op,
     final Expression left, final Expression right)
  {
    super(loc);
    this.op = op;
    this.left = left;
    this.right = right;
  }

  /** Retrieve the specific binary operator represented by the node.
   *
   *  @return the specific binary operator represented by the node.
   */
  public Binop getOp()
  {
    return op;
  }

  /** Convert operator kind to (Java) String for displaying.
   *
   *  @return Java string for the name of this operator
   */
  public String getOpString()
  {
    return op.toString();
  }

  /** Get the left subtree of the node.
   *
   *  @return the left subtree of the node.
   */
  public Expression getLeft()
  {
    return left;
  }

  /** Set the left subtree of the node.
   *
   *  @param left the new left subtree of the node.
   */
  public void setLeft(Expression left)
  {
    this.left = left;
  }

  /** Get the right subtree of the node.
   *
   *  @return the right subtree of the node.
   */
  public Expression getRight()
  {
    return right;
  }

  /** Set the right subtree of the node.
   *
   *  @param right the new right subtree of the node.
   */
  public void setRight(Expression right)
  {
    this.right = right;
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}
