
package tc.compiler.tree;

import tc.compiler.Location;
import tc.compiler.tree.visit.TreeVisitor;

/**
 * AST class declaration node.
 *
 */
public final class ClassDeclaration extends Node
{
  /** Construct a class declaration tree node.
   *
   *  @param loc the source code location of the class declaration.
   */
  public ClassDeclaration(final Location loc)
  {
    super(loc);
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}

