package tc.compiler.tree;

import tc.compiler.Location;
import tc.compiler.tree.visit.TreeVisitor;
import tc.compiler.tree.type.*;
import tc.compiler.tree.Identifier;
import java.util.List;
import java.util.ArrayList;

/**
 * AST declaration statement node.
 *
 */
public final class DeclarationStatement extends Statement
{
    private Type type;
    private List<Identifier> declarations;
    private List<Integer> dimList;

    /** Create a statement tree node
     * @param loc location in source code
     * @param type type of declarations
     * @param decls list of entities being declared
     * @param dimList list of dimensions associated with array type vars
     */
     public DeclarationStatement(final Location loc, final Type type, final List<Identifier> decls, final List<Integer> dimList)
     {
         super(loc);
         this.type = type;
         this.declarations = decls;
         this.dimList = new ArrayList<Integer>();
         
         //build the dimension list with the correct array depths
         for(int i = 0; i < dimList.size(); i++)
         {
            int addDims = 0; 

            //if the overall type of the declarattion is an array, add its specified depth to
            //the depth of the individual declaration
            if (type instanceof ArrayType)
            {
                addDims = ((ArrayType) type).getDepth();
            }
            this.dimList.add(new Integer(dimList.get(i).intValue() + addDims));
         }
     }

     /** get type of declarations
     * @return Type
      */
    public Type getType() 
    {
        return this.type;
    }

    /** gets list of declared entitites
    * @return List
     */
    public List<Identifier> getDeclarations() 
    {
        return this.declarations;
    }

    /** gets list of dimensions declared
    * @return List
     */
    public List<Integer> getDimensionList() 
    {
        return this.dimList;
    }

    /** Apply a visitor to the node.
    *
    *  @param visitor the visitor to apply.
    *
    *  @return the value generated by the visitor.
    */
    @Override public <T> T apply(TreeVisitor<T> visitor)
    {
        return visitor.visit(this);
    }
}