
package tc.compiler.tree;

import tc.compiler.Location;
import tc.compiler.tree.visit.TreeVisitor;
import tc.compiler.tree.Statement;

/**
 * AST empty statement node.
 *
 */
public final class EmptyStatement extends Statement
{

  /** Construct a EmptyStatement (aka do nothing).
   *
   *  @param loc the source code location of the statement.
   */
  public EmptyStatement(final Location loc)
  {
    super(loc);
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}

